/**
 * Generates src/ui/components/icons/iconPaths.generated.ts — the inline-SVG
 * path data backing MaterialIcon.tsx.
 *
 * Why generated + committed: icons are baked into the JS bundle so the app
 * renders identically offline. (The previous Material Symbols icon font came
 * from Google Fonts as ~50 unicode-range slices; the slice carrying the
 * ligature data intermittently missed the SW cache, and icons degraded to raw
 * ligature text like "cloud_off" offline.)
 *
 * Usage: npm run gen:icons  (run after adding an icon name to ICONS below)
 *
 * The script also fail-closes on:
 *  - icon names used in src/ but missing from ICONS (add them here)
 *  - any reintroduction of the .material-symbols-outlined font class
 */
import { mkdirSync, readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PKG_DIR = join(ROOT, 'node_modules', '@material-symbols', 'svg-400', 'outlined');
const OUT_FILE = join(ROOT, 'src', 'ui', 'components', 'icons', 'iconPaths.generated.ts');
const SRC_DIR = join(ROOT, 'src');

// Every icon name rendered via MaterialIcon (or passed through dynamic maps:
// navItems/navActions, Welcome slides, SLOT_ICON, getSourceIcon, page-level
// ternaries). Names are Material Symbols "outlined" set, weight 400.
const ICONS = [
  'add',
  'add_circle',
  'all_inclusive',
  'arrow_back',
  'arrow_forward',
  'auto_awesome_motion',
  'bedtime',
  'calculate',
  'calendar_today',
  'celebration',
  'check',
  'check_circle',
  'chevron_right',
  'close',
  'cloud_done',
  'cloud_off',
  'cloud_upload',
  'content_copy',
  'dark_mode',
  'delete',
  'delete_forever',
  'download',
  'edit',
  'edit_calendar',
  'edit_document',
  'error',
  'event',
  'flag',
  'group_add',
  'groups',
  'history',
  'home',
  'info',
  'ios_share',
  'keyboard_arrow_down',
  'keyboard_arrow_up',
  'library_books',
  'link',
  'local_fire_department',
  'location_on',
  'location_searching',
  'lock',
  'logout',
  'mobile',
  'mobile_vibrate',
  'mosque',
  'my_location',
  'nightlight',
  'numbers',
  'person',
  'play_arrow',
  'radio_button_checked',
  'radio_button_unchecked',
  'refresh',
  'replay',
  'save',
  'schedule',
  'search',
  'search_off',
  'settings',
  'share',
  'skip_next',
  'spa',
  'stop_circle',
  'summarize',
  'sync',
  'system_update_alt',
  'target',
  'task_alt',
  'touch_app',
  'track_changes',
  'translate',
  'trending_up',
  'tune',
  'upload',
  'vpn_key',
  'wb_twilight',
  'wifi_off',
];

function readSvg(name) {
  const file = join(PKG_DIR, `${name}.svg`);
  const svg = readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!viewBox || ds.length === 0) {
    throw new Error(`${name}.svg: could not parse viewBox/path data`);
  }
  return { viewBox, d: ds.join(' ') };
}

function readFill(name) {
  try {
    return readSvg(name + '-fill');
  } catch {
    return null; // no filled variant for this icon
  }
}

// The icon={...} ternary scan captures every quoted token in the expression,
// including comparison values like `plan.period === 'daily'`. These tokens are
// state values, not icons — list any new ones here (the scan fails loudly so a
// genuinely new icon is never silently skipped).
const NON_ICON_LITERALS = new Set(['locating', 'daily', 'synced', 'pending']);

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, files);
    } else if (/\.(ts|tsx)$/.test(entry) && !entry.endsWith('.generated.ts')) {
      files.push(full);
    }
  }
  return files;
}

// 1. Build the path map ------------------------------------------------------
const viewBoxes = new Set();
const entries = [];
for (const name of ICONS) {
  const { viewBox, d } = readSvg(name);
  viewBoxes.add(viewBox);
  const fill = readFill(name);
  // The filled variant is only worth its bytes when it's actually a different
  // design (many -fill files are identical to the outline).
  const fillD = fill && fill.d !== d ? fill.d : undefined;
  entries.push({ name, d, fillD });
}
if (viewBoxes.size !== 1) {
  throw new Error(`Expected one uniform viewBox, got: ${[...viewBoxes].join(', ')}`);
}
const VIEWBOX = [...viewBoxes][0];

const rendered = entries
  .map(({ name, d, fillD }) => {
    const lines = [`  ${name}: {\n    d: '${d}',`];
    if (fillD) lines.push(`    fill: '${fillD}',`);
    lines.push('  },');
    return lines.join('\n');
  })
  .join('\n');

const out = `/* eslint-disable */
/**
 * GENERATED by scripts/generate-icons.mjs from @material-symbols/svg-400
 * (weight 400) — DO NOT EDIT. Regenerate with \`npm run gen:icons\` after
 * adding a name to the ICONS list in that script.
 *
 * Path data on Google's 960-unit grid (uniform viewBox "${VIEWBOX}"),
 * rendered at 1em by MaterialIcon so font-size classes size the icon.
 * \`fill\` is omitted where the filled variant equals the outline.
 */
export const ICON_VIEWBOX = '${VIEWBOX}';

export interface IconPathSet {
  d: string;
  fill?: string;
}

export const ICON_PATHS: Readonly<Record<string, IconPathSet>> = {
${rendered}
};
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, out);
const withFill = entries.filter((e) => e.fillD).length;
console.log(
  `iconPaths.generated.ts: ${entries.length} icons (${withFill} with a distinct fill variant), viewBox ${VIEWBOX}`
);

// 2. Fail-closed coverage scan ----------------------------------------------
const srcFiles = walk(SRC_DIR);
const used = new Map(); // name -> first file
const patterns = [
  /\bicon=\{?["']([a-z][a-z0-9_]*)["']/g,
  /\bicon:\s*["']([a-z][a-z0-9_]*)["']/g,
  // ternaries inside icon={...}: icon={cond ? 'a' : 'b'}
  /\bicon=\{[^{};]*?\}/g,
];
for (const file of srcFiles) {
  const text = readFileSync(file, 'utf8');
  for (const pattern of patterns) {
    for (const m of text.matchAll(pattern)) {
      for (const lit of m[0].matchAll(/["']([a-z][a-z0-9_]*)["']/g)) {
        const name = lit[1];
        if (NON_ICON_LITERALS.has(name)) continue;
        if (!used.has(name)) used.set(name, relative(ROOT, file));
      }
    }
  }
}
const known = new Set(ICONS);
const missing = [...used.keys()].filter((n) => !known.has(n));
if (missing.length > 0) {
  console.error(
    `\nIcons used in src/ but missing from the ICONS list in scripts/generate-icons.mjs:\n` +
      missing.map((n) => `  - ${n}  (first use: ${used.get(n)})`).join('\n') +
      `\nAdd them to ICONS and rerun npm run gen:icons.`
  );
  process.exit(1);
}

// 3. Guard against the icon webfont sneaking back in ------------------------
const fontFiles = walk(SRC_DIR).map((f) => relative(ROOT, f));
fontFiles.push('index.html');
const fontRegressions = fontFiles.filter((f) =>
  readFileSync(join(ROOT, f), 'utf8').includes('material-symbols-outlined')
);
if (fontRegressions.length > 0) {
  console.error(
    `\n.material-symbols-outlined (the icon webfont that breaks offline) found in:\n` +
      fontRegressions.map((f) => `  - ${f}`).join('\n') +
      `\nUse <MaterialIcon> (inline SVG) instead.`
  );
  process.exit(1);
}
console.log(`coverage scan: ${used.size} icon names referenced in src/, all covered`);
